### ISSUE TITLE
Issue 1 from xc918

### ISSUE THREAD

**Issue by xc918** [nyu-cds/yg1281_assignment3#1]
First, I saw the running time of nbody_opt.py is 41.44s. I tried yg1281's code, and I got 28.8s, which is under 30s. Therefore, I suggest the author put name at the beginning.

**Comment by xc918** [comment]
Second, I found there is a function called _update_vs_ which is outside the function _advance_. This could cause function call overhead. I modified the code by moving the content of _update_vs_ in to _advance_, and I got the running time is 25.7s, which is faster.

**Comment by guiyuting** [comment]
Solved.

**Comment by guiyuting** [comment]
fixed
